# Generated by Django 2.0.2 on 2018-03-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='date_published'),
        ),
    ]
