# Generated by Django 2.0.2 on 2018-03-08 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_product_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='erstellt'),
        ),
        migrations.AddField(
            model_name='product',
            name='modified',
            field=models.DateTimeField(blank=True, null=True, verbose_name='bearbeitet'),
        ),
    ]
