# Generated by Django 2.0.2 on 2018-03-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20180308_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='created',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Erstellt'),
        ),
    ]
